# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: ghnod CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: gist-box
        uses: yadavgulshan/gist-box@v1.0.0
env:
  GH_TOKEN: ${{ secrets.GH_TOKEN }}
  GIST_ID: ${{ secrets.GIST_ID }}
  CONSIDER_PRIVATE: ${{ secrets.CONSIDER_PRIVATE }}
